### ISSUE TITLE
[fuzzman] Fix possible division by zero 

### ISSUE THREAD

**Issue by mimicria** [fuzzah/fuzzaide#1]
Hi!
When fuzzing starts slowly (with many inputs) and fuzzer_stats may contain 0 in paths, there is a chance to zero division
So fix is in [this commit](https://github.com/fuzzah/fuzzaide/commit/947e2099401e43cd5b98b07088bee8c5aa3023d4)

**Comment by fuzzah** [comment]
Thanks. I'll look into it.
You might as well be interested in [this project](https://github.com/gardatech/bugbane) which contains a tool similar to fuzzman.
