### ISSUE TITLE
[fuzzman] Fix fuzzer_stat entries

### ISSUE THREAD

**Issue by mimicria** [fuzzah/fuzzaide#2]
In AFLplusplus 4.00c+ versions [were renamed](https://github.com/AFLplusplus/AFLplusplus/releases/tag/4.00c) several UI and fuzzer_stat entries
So fix is in [this commit](https://github.com/fuzzah/fuzzaide/commit/224b942bd9933c5d8e71f7d8484de596a3846813)

**Comment by fuzzah** [comment]
Thank you for contribution!
The fix provided just won't do as it drops support for previous versions of AFL :)
Still I'll look into implementing better solution.
